
#################################
#           Fading              #
#################################
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

#################################
#           Opacity             #
#################################
inactive-opacity = 0.85;
frame-opacity = 1.0;
inactive-opacity-override = false;
active-opacity = 1.0;

# Gjør terminaler og menyer gjennomsiktige, men hold spill/video opakt
focus-exclude = [ "class_g = 'Cairo-clock'" ];

opacity-rule = [
  "100:class_g = 'St' && !focused",
  "100:class_g = 'Alacritty' && focused",
  "90:class_g = 'Alacritty' && !focused",
  "100:class_g = 'Firefox'",
  "100:class_g = 'Steam'"
];

#################################
#       NVIDIA Spesifikt        #
#################################
vsync = true;
dithered-present = false;
mark-wmwin-focused = true;
mark-ovlp-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
